# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_RIGOL_HDCODE_GPIO) += hdcode_gpio.o
obj-$(CONFIG_RIGOL_FG_M2C_GPIO) += fg_m2c_gpio.o
obj-$(CONFIG_RIGOL_SPI2PLL_LXM2582_GPIO) += spi2pll_lxm2582_gpio.o
